// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vqzcdnfpxkdedonaunox.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZxemNkbmZweGtkZWRvbmF1bm94Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE4MTA4NzUsImV4cCI6MjA2NzM4Njg3NX0.YQoTh6gM-HKjt6oZ2OHKVfXgtxQVqeJbNOEZAsWVKJ8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});